### ISSUE TITLE
syntax error, unexpected keyword_rescue

### ISSUE THREAD

**Issue by cdevrell-kallidus** [dsalahutdinov/yabeda-http_requests#5] opened 2021-10-04 08:57 UTC
After adding `gem 'yabeda-http_requests'` to my Gemfile, I am getting this error when trying to run any rails command and precompiling.

I am using ruby version 2.3.1 and rails version 5.1.7.

The bundle install command appears to run okay.

Are there any prerequisites required for the yabeda_http_requests gem?

My Gemfile also contains a few other Yabeda suite gems and these are all working okay.

```
#yabeda
gem 'yabeda-prometheus'
gem 'yabeda-sidekiq'
gem 'yabeda-rails'
gem 'yabeda-puma-plugin'
gem 'yabeda-http_requests'
```

Error message:

```
#54 0.586 Running rails i18n:js:export
#54 6.399 rails aborted!
#54 6.399 SyntaxError: /usr/local/rvm/gems/ruby-2.3.1@app_5.1.7/gems/sniffer-0.4.0/lib/sniffer/adapters/httpclient_adapter.rb:34: syntax error, unexpected keyword_rescue, expecting keyword_end
#54 6.399         rescue HTTPClient::RetryableResponse => e
#54 6.399               ^
#54 6.399 /usr/local/rvm/gems/ruby-2.3.1@app_5.1.7/gems/sniffer-0.4.0/lib/sniffer/adapters/httpclient_adapter.rb:34: syntax error, unexpected =>
#54 6.399         rescue HTTPClient::RetryableResponse => e
#54 6.399                                                ^
#54 6.399 /usr/local/rvm/gems/ruby-2.3.1@app_5.1.7/gems/railties-5.1.7/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
#54 6.399 /usr/local/rvm/gems/ruby-2.3.1@app_5.1.7/gems/railties-5.1.7/lib/rails/commands/rake/rake_command.rb:18:in `perform'
#54 6.399 /usr/local/rvm/gems/ruby-2.3.1@app_5.1.7/gems/railties-5.1.7/lib/rails/command.rb:46:in `invoke'
#54 6.399 /usr/local/rvm/gems/ruby-2.3.1@app_5.1.7/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
#54 6.399 bin/rails:4:in `require'
#54 6.399 bin/rails:4:in `<main>'
#54 6.399 (See full trace by running task with --trace)
```

**Comment by Envek** [comment] 2021-10-04 13:31
Gem [Sniffer](https://github.com/aderyabin/sniffer) (which is dependency for yabeda-http_requests) in version 0.4.0 uses Ruby syntax added in Ruby 2.5 (rescue in blocks), so either **downgrade sniffer version** or **upgrade your Ruby**.

As Ruby 2.3 is already [reached its EOL in 2019](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/) (more than 2 years ago!), I decided to drop support for it and in the next version yabeda-http_requests will require at least Ruby 2.5 in its gemspec.

Duplicate of #1

**Closed as completed** 2021-10-04 13:32 UTC
